### ISSUE TITLE
The cleaning of the SSL_* apis

### ISSUE THREAD

**Issue by wbl** [quictls/quictls#108]
After landing https://github.com/quictls/quictls/pull/97 we have a number of useless SSL functions that were needed for QUIC but not guarded by feature flags and now do nothing. It requires looking at the documentation to figure out what they are.

I propose removing them. There are also changes to the BIO layer that require some thought.

For reference the list (compiled from libssl.num and some reading on each one):
* SSL_get_rpoll_descriptor
* SSL_get_wpoll_descriptor
* SSL_(set/get)_blocking_mode
* SSL_set1_initial_peer_addr
* SSL_net_read_desired/net_write_desired
* SSL_handle_events, but this does something on DTLS connections also
* SSL_shutdown_ex
* SSL_stream_conclude
* SSL_new_stream
* SSL_get0_connection
* SSL_is_connection (sic)
* SSL_get_stream_type
* SSL_get_stream_id
* SSL_set_default_stream_mode
* SSL_stream_*
* SSL_get_conn_close_info
* SSL_set_incoming_stream_policy
* SSL_get_event_timeout
* SSL_is_stream_local
* SSL_write_ex2
* SSL_get_value_uint
* SSL_set_value_uint
* SSL_poll

**Comment by richsalz** [comment]
I started removing QUIC documentation (PR in progress), and tugging on that thread means I am removing some of these as well.  So maybe wait for my PR.

**Comment by richsalz** [comment]
#109 does lots of it.

It doesn't remove the `isquic` variable in a `apps/s_client.c`
