### ISSUE TITLE
Remove ENGINE support?

### ISSUE THREAD

**Issue by richsalz** [quictls/quictls#24]
Providers are the new world order.

The only one I think we care about is gost.  But maybe we should ask around first.

**Comment by wbl** [comment]
I don't think we can be more aggressive than OpenSSL on this one without really understanding the ecosystem.

**Comment by botovq** [comment]
The ecosystem isn't quite ready for full removal, unfortunately. A [few things][1] don't honor `OPENSSL_NO_ENGINE`
and we needed to [stub out][2] a few functions to avoid too many patches in our ports tree: https://man.openbsd.org/ENGINE_new.

There's also a PR that resurfaced proposing to expose ENGINE bindings in rust-openssl: https://github.com/sfackler/rust-openssl/pull/2304

[1]: https://github.com/openbsd/src/blob/f8f7dc1f1132b5aeb0dfc6c92da9ba96b923f6b9/lib/libcrypto/engine/engine.h#L92
[2]: https://github.com/openbsd/src/blob/f8f7dc1f1132b5aeb0dfc6c92da9ba96b923f6b9/lib/libcrypto/engine/engine_stubs.c

**Comment by wbl** [comment]
Closing as we can't do it. Will reopen a few years later, hopefully with different answer.
