### ISSUE TITLE
Remove no-dh, etc., configuration option

### ISSUE THREAD

**Issue by richsalz** [quictls/quictls#30]
DH, ECDH, DHE, DHE_KX should all be assumed and it should not be possible to turn it off.

#29 turns it off from the daily CI build.  (Yeah, perhaps should be a separate PR; oh well)

**Comment by wbl** [comment]
There probably are some other ones we should tweak. Probably has to involve removing the ifdefs as well.

**Comment by richsalz** [comment]
See #39
