### ISSUE TITLE
enable-fips should just warn/exit

### ISSUE THREAD

**Issue by richsalz** [quictls/quictls#31]
QuicTLS is not providing a FIPS-enabled module that has been verified. We should not build the FIPS module.

It might be nice to run the FIPS tests against the openSSL module however.

**Comment by wbl** [comment]
Once you replace the modules you would have one that is FIPS.

Agreed on the desirability of FIPS tests with OpenSSL module

**Comment by richsalz** [comment]
> Once you replace the modules you would have one that is FIPS.

Do you mean copy over the files from OpenSSL after they do FIPS config?  Cute hack.

**Comment by wbl** [comment]
Yeah, that's already what we do with 3.1 and 3.0

**Comment by richsalz** [comment]
With #96 'build the fips container' is gone. The `fips-stuff` tag points to the commit that did it, in case we ever need to bring it back.  Closing.
