### ISSUE TITLE
Deprecate X509_OBJECT_up_ref_count

### ISSUE THREAD

**Issue by richsalz** [quictls/quictls#77]
Import of openssl/issue/21121 reported by davidben

title:	Deprecate X509_OBJECT_up_ref_count
state:	OPEN
author:	davidben
labels:	branch: master, help wanted, triaged: feature
comments:	0
assignees:	
projects:	
milestone:	
number:	21121
--
With `X509_OBJECT` opaque, I don't believe there is anything useful a caller can do with `X509_OBJECT_up_ref_count`. Despite the name, it doesn't increase the ref-count of the `X509_OBJECT` itself (`X509_OBJECT` is not ref-counted). It bumps the refcount of whatever object is stored in the `X509_OBJECT`, without returning the object or anything.

It's used within the library right after copying some value into an `X509_OBJECT`, to update the ref-count accordingly. But that's to used in the course of getting an `X509_OBJECT` into a consistent state, but the public APIs should handle that already.

**Comment by richsalz** [comment]
Not going to do this,  for compatibility with apps/foreign language bindings, etc based on feedback from TB

**Comment by botovq** [comment]
Actually, I think we can remove this. I can't find any use of it in our ports tree or on codesearch and the reason we still have it is simply that I hadn't noticed that it was unused.
